<?php

namespace App\Enum;

use ReflectionClass;

enum PermissionEnum: string {
    case CREATE = 'Iniciar Sesion';
    case READ = 'read';
    case UPDATE = 'update';
    case DELETE = 'delete';
    case RUTA_RECUPERAR_CONTRASENIA = 'RUTA_RECUPERAR_CONTRASENIA';
    case RUTA_CONFIGURACIONES = 'RUTA_CONFIGURACIONES';

    //permisos aduana
    case RUTA_ADUANA = 'RUTA_ADUANAS';
    case LISTAR_ADUANA = 'LISTAR_ADUANAS';
    case CREAR_ADUANA = 'CREAR_ADUANA';
    case ACTUALIZAR_ADUANA = 'ACTUALIZAR_ADUANA';

    //permisos facturas
    case RUTA_FACTURA = 'RUTA_FACTURAS';
    case LISTAR_FACTURAS = 'LISTAR_FACTURAS';
    case CREAR_FACTURA = 'CREAR_FACTURA';
    case ACTUALIZAR_FACTURA = 'ACTUALIZAR_FACTURA';

    //permisos clases
    case RUTA_CLASE = 'RUTA_CLASES';
    case LISTAR_CLASES = 'LISTAR_CLASES';
    case CREAR_CLASE = 'CREAR_CLASE';
    case ACTUALIZAR_CLASE = 'ACTUALIZAR_CLASE';

    //permisos oficial
    case RUTA_OFICIAL = 'RUTA_OFICIALES';
    case LISTAR_OFICIALES = 'LISTAR_OFICIALES';
    case CREAR_OFICIAL = 'CREAR_OFICIAL';
    case ACTUALIZAR_OFICIAL = 'ACTUALIZAR_OFICIAL';

    //permisos institucion

    case RUTA_INSTITUCIONES = 'RUTA_INSTITUCIONES';
    case LISTAR_INSTITUCIONES = 'LISTAR_INSTITUCIONES';
    case CREAR_INSTITUCION = 'CREAR_INSTITUCION';
    case ACTUALIZAR_INSTITUCION = 'ACTUALIZAR_INSTITUCION';

    //permisos firmante

    case RUTA_FIRMA = 'RUTA_FIRMA';
    case LISTAR_FIRMANTES = 'LISTAR_FIRMANTES';
    case CREAR_FIRMANTE = 'CREAR_FIRMANTE';
    case ACTUALIZAR_FIRMANTE = 'ACTUALIZAR_FIRMANTE';


    //permisos identificador gestion
    case RUTA_IDENTIFICADOR_GESTION = 'RUTA_IDENTIFICADORES_GESTION';
    case LISTAR_IDENTIFICADOR_GESTION = 'LISTAR_IDENTIFICADOR_GESTON';
    case CREAR_IDENTIFICADOR_GESTION = 'CREAR_IDENTIFICADOR_GESTION';
    case ACTUALIZAR_IDENTIFICADOR_GESTION = 'ACTUALIZAR_IDENTIFICADOR_GESTION';

    //FRANQUICIAS

    case RUTA_FRANQUICIA = 'RUTA_FRANQUICIAS';
    case CREAR_FRANQUICIA = 'CREAR_FRANQUICIA';
    case ENVIAR_FRANQUICIA_REVISION = 'ENVIAR_FRANQUICIA_REVISION';
    case ACTUALIZAR_FRANQUICIA = 'ACTUALIZAR_FRANQUICIA';
    case VER_DETALLE_FRANQUICIA = 'VER_DETALLE_FRANQUICIA';
    case LISTAR_FRANQUICIAS = 'LISTAR_FRANQUICIAS';
    case CREAR_BORRADOR = 'CREAR_BORRADOR';
    case OBSERVAR_FRANQUICIA = 'OBSERVAR_FRANQUICIA';
    case SUBIR_ARCHIVOS_FRANQUICIA = 'SUBIR_ARCHIVOS_FRANQUICIA';
    case VER_ARCHIVOS_FRANQUICIA = 'VER_ARCHIVOS_FRANQUICIA';
    case LISTAR_ARCHIVOS_FRANQUICIA = 'LISTAR_ARCHIVOS_FRANQUICIA';
    case ELIMINAR_ARCHIVOS_FRANQUICIA = 'ELIMINAR_ARCHIVOS_FRANQUICIA';
    case SOLVENTAR_FRANQUICIA = 'SOLVENTAR_FRANQUICIA';
    case APROBAR_FRANQUICIA = 'APROBAR_FRANQUICIA';
    case PREVISUALIZAR_DOCUMENTO_FRANQUICIA = 'PREVISUALIZAR_DOCUMENTO_FRANQUICIA';
    case ACTUALIZAR_OBSERVACION_FRANQUICIA = 'ACTUALIZAR_OBSERVACION_FRANQUICIA';
    case GESTIONAR_FECHAS = 'GESTIONAR_FECHAS';


    //permisos user
    case RUTA_USUARIOS = 'RUTA_USUARIOS';
    case LISTAR_USERS = 'LISTAR_USUARIOS';
    case CREAR_USER = 'CREAR_USUARIO';
    case ACTUALIZAR_USER = 'ACTUALIZAR_USUARIO';
    case DESBLOQUEAR_USER = 'DESBLOQUEAR_USUARIO';

    //para roles
    case RUTA_ROLES = 'RUTA_ROLES';
    case RUTA_PERMISOS = 'RUTA_PERMISOS';
    case LISTAR_PERMISOS = 'LISTAR_PERMISOS';
    case LISTAR_ROLES = 'LISTAR_ROLES';
    case CREAR_ROL = 'CREAR_ROL';
    case ACTUALIZAR_ROL = 'ACTUALIZAR_ROL';
    case RUTA_USUARIOS_ROLES = 'RUTA_USUARIOS_ROLES';
    case ANULAR_FRANQUICIA = 'ANULAR_FRANQUICIA';

    // Reportes
    case RUTA_REPORTES = 'RUTA_REPORTES';
    case GENERAR_REPORTES = "GENERAR_REPORTES";

    //Clasificacion
    case PUNTUAR_FRANQUICIAS = 'PUNTUAR_FRANQUICIAS';
    case VER_PUNTAJE_FRANQUICIAS = 'VER_PUNTAJE_FRANQUICIAS';
    case GUARDAR_OBSERVACION = 'GUARDAR_OBSERVACION';
    case LISTAR_OBSERVACIONES = 'LISTAR_OBSERVACIONES';
    case PREVISUALIZAR_ARCHIVO_OBSERVACION = 'PREVISUALIZAR_ARCHIVO_OBSERVACION';
    case ELIMINAR_OBSERVACION = 'ELIMINAR_OBSERVACION';
    case VER_PROMEDIO_ENTIDAD = 'VER_PROMEDIO_ENTIDAD';
    case VER_PROMEDIO_ENTIDADES = 'VER_PROMEDIO_ENTIDADES';
    case LISTAR_CLASIFICACIONES = 'LISTAR_CLASIFICACIONES';



    // VISITAS DE CAMPOS

    case LISTAR_VISITAS_CAMPOS = 'LISTAR_VISITAS_CAMPOS';
    case DETALLE_VISITA_CAMPO = 'DETALLE_VISITA_CAMPO';
    case CREAR_VISITA_CAMPO = 'CREAR_VISITA_CAMPO';
    case EDITAR_VISITA_CAMPO = 'EDITAR_VISITA_CAMPO';
    case DETALLE_SEGUIMIENTO_VISITA_CAMPO = 'DETALLE_SEGUIMIENTO_VISITA_CAMPO';
    case ELIMINAR_VISITA_CAMPO = 'ELIMINAR_VISITA_CAMPO';
    case LISTAR_SEGUIMIENTOS_VISITA_CAMPO = 'LISTAR_SEGUIMIENTOS_VISITA_CAMPO';
    case GENERAR_REPORTE_VISITA_CAMPO = 'IMPRIMIR_REPORTE_VISITA_CAMPO';
    case GENERAR_REPORTES_VISITA_CAMPO = 'IMPRIMIR_REPORTES_VISITA_CAMPO';

    public static function toArray(): array
    {
        return (new ReflectionClass(self::class))->getConstants();
    }


}
